name: flutter_carpooling
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  animate_do: ^1.7.5
  characters: ^1.0.0
  flutter_spinkit: 4.1.2
  cupertino_icons: 0.1.2
  smooth_star_rating: 1.1.1
  keyboard_visibility: 0.5.6
  flutter_speed_dial: 1.2.5
  font_awesome_flutter: 8.10.0
  data_connection_checker: 0.3.4

  path: ^1.6.4
  camera: ^0.5.8+17
  storage_path: ^0.2.0
  path_provider: ^1.4.2
  flutter_native_image: ^0.0.5
  
  intl: 0.16.1
  http: 0.12.2
  provider: ^4.3.2+2
  shared_preferences: 0.5.12+2

  firebase_core: ^0.5.2
  firebase_auth: ^0.18.2
  firebase_storage: ^5.0.1
  cloud_firestore: ^0.14.3+1

  geocoder: ^0.2.1
  google_maps_flutter: ^1.0.3
  flutter_google_places: 0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/img/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/WorkSans-Medium.ttf

    - family: WorkSansRegular
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf

    - family: WorkSansLight
      fonts:
        - asset: assets/fonts/WorkSans-Light.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
